---
  - name: "[APACHE] Add Repo"
    apt_repository:
      repo: "ppa:ondrej/apache2"
      state: present
      
  - name: "[APACHE] Install apache and modules"
    apt:
      name: ['apache2']
      state: present

  - name: "[APACHE] Enable modules"
    apache2_module:
      state: present
      name: "{{ item }}"
    with_items:
      - proxy
      - proxy_http
      - proxy_http2
      - rewrite
      - md
      - ssl